In [1]:
import pandas as pd
from pathlib import Path

In [17]:
PROJECT_ROOT=Path.cwd().parent
RAW_DIR=PROJECT_ROOT / "data" / "raw"
print(PROJECT_ROOT)
print(list(RAW_DIR.glob("*.csv")))

/Users/zemfiraramazanova/PycharmProjects/financial-complaints-radar
[PosixPath('/Users/zemfiraramazanova/PycharmProjects/financial-complaints-radar/data/raw/complaints-2024.csv'), PosixPath('/Users/zemfiraramazanova/PycharmProjects/financial-complaints-radar/data/raw/complaints-2023.csv')]

In [13]:
data_files = sorted(RAW_DIR.glob("*.csv"))

## Ознакомление с полями и видом таблиц

In [14]:
for file in data_files:
    sample = pd.read_csv(file, nrows=3)

    print(f"\n Файл: {file.name}")
    print("Поля:")
    print(sample.columns.tolist())
    display(sample)

 Файл: complaints-2023.csv
Поля:
['Date received', 'Product', 'Sub-product', 'Issue', 'Sub-issue', 'Company public response', 'Company', 'State', 'ZIP code', 'Tags', 'Submitted via', 'Date sent to company', 'Company response to consumer', 'Timely response?', 'Complaint ID']

,Date received,Product,Sub-product,Issue,Sub-issue,Company public response,Company,State,ZIP code,Tags,Submitted via,Date sent to company,Company response to consumer,Timely response?,Complaint ID
0,2023-03-11T14:52:49.000Z,Checking or savings account,Savings account,Problem with a lender or other company chargin...,Transaction was not authorized,Company has responded to the consumer and the ...,"CITIBANK, N.A.",NY,11367,Older American,Web,2023-03-11T15:09:00.000Z,Closed with explanation,Yes,6681481
1,2023-03-11T14:55:02.000Z,Debt collection,Credit card debt,False statements or representation,Told you not to respond to a lawsuit they file...,Company has responded to the consumer and the ...,"CITIBANK, N.A.",NC,28079,Servicemember,Web,2023-03-11T15:47:07.000Z,Closed with explanation,Yes,6681477
2,2023-03-11T15:30:09.000Z,Debt collection,Credit card debt,Attempts to collect debt not owed,Debt was result of identity theft,NaN,"EQUIFAX, INC.",IL,60473,NaN,Web,2023-03-11T15:33:11.000Z,Closed with explanation,Yes,6681419

 Файл: complaints-2024.csv
Поля:
['Date received', 'Product', 'Sub-product', 'Issue', 'Sub-issue', 'Company public response', 'Company', 'State', 'ZIP code', 'Tags', 'Submitted via', 'Date sent to company', 'Company response to consumer', 'Timely response?', 'Complaint ID']

,Date received,Product,Sub-product,Issue,Sub-issue,Company public response,Company,State,ZIP code,Tags,Submitted via,Date sent to company,Company response to consumer,Timely response?,Complaint ID
0,2024-01-03T14:57:29.000Z,Checking or savings account,Checking account,Problem with a lender or other company chargin...,Transaction was not authorized,Company believes it acted appropriately as aut...,NAVY FEDERAL CREDIT UNION,VA,22191,Servicemember,Web,2024-01-03T15:25:33.000Z,Closed with explanation,Yes,8101341
1,2024-01-01T02:35:47.000Z,Debt collection,Medical debt,Attempts to collect debt not owed,Debt was result of identity theft,Company has responded to the consumer and the ...,"TRANSUNION INTERMEDIATE HOLDINGS, INC.",CA,90008,NaN,Web,2024-01-01T04:05:54.000Z,Closed with non-monetary relief,Yes,8085329
2,2024-01-01T00:24:12.000Z,Checking or savings account,Checking account,Problem caused by your funds being low,Bounced checks or returned payments,Company has responded to the consumer and the ...,FIRST TECHNOLOGY FEDERAL CREDIT UNION,TX,76052,NaN,Web,2024-01-03T21:07:17.000Z,Closed with explanation,Yes,8085678

## Проверка временных рамок и оценка количества записей

In [15]:
for file in data_files:
    data = pd.read_csv(
        file,
        parse_dates=["Date received"],
        low_memory=False,
    )

    print(f"\n{file.name}")
    print(f"Количество строк: {len(data):,}")
    print(f"Количество столбцов: {data.shape[1]}")
    print(
        f"Период: {data['Date received'].min().date()} — "
        f"{data['Date received'].max().date()}"
    )
    print("Продукты:")
    print(data["Product"].value_counts())

complaints-2023.csv
Количество строк: 40,387
Количество столбцов: 15
Период: 2023-01-01 — 2023-06-30
Продукты:
Product
Checking or savings account                           26082
Debt collection                                        7530
Money transfer, virtual currency, or money service     6775
Name: count, dtype: int64

complaints-2024.csv
Количество строк: 97,565
Количество столбцов: 15
Период: 2024-01-01 — 2024-06-30
Продукты:
Product
Debt collection                                       64738
Checking or savings account                           24874
Money transfer, virtual currency, or money service     7953
Name: count, dtype: int64

Вызывает интерес рост количества обращений в 2024 году более чем 2 раза относительно того же отрезка времени 2023 года